---
stages:
  - build
  - publish

default:
  image: python:3.6
  cache:
    paths:
      - ./venv
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate


install-deps:
  stage: .pre
  extends: .rnd-dev-runner
  script:
    - pip install -U setuptools twine wheel
  only:
    - develop
    - tags


build-prod:
  extends: .build-package
  script:
    - python setup.py sdist bdist_wheel
  only:
    - tags


build-dev:
  extends: .build-package
  script:
    - VERSION_POSTFIX=".dev$(date +%Y%m%d%H%M%S)"
    - echo "$(cat version)${VERSION_POSTFIX}" > version
    - python setup.py sdist bdist_wheel
  only: 
    - develop


publish:
  stage: publish
  extends: .rnd-dev-runner
  script:
    - twine upload --repository-url ${PYPI_URL} -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*
  only:
    - tags
    - develop


.build-package:
  extends: .rnd-dev-runner
  stage: build
  dependencies:
    - install-deps
  artifacts:
    paths:
      - ./dist/
    untracked: true
    expire_in: 1 day

.rnd-dev-runner:
  tags:
    - rnd-dev
