---
stages:
  - build
  - test
  - publish

default:
  image: python:3.6
  cache:
    paths:
      - ./venv
  before_script:
    - python3 -V
    - python3 -m pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate


install-deps:
  stage: .pre
  extends: .rnd-dev-runner
  script:
    - pip install -U setuptools twine wheel
  only:
    - develop
    - tags


build-prod:
  extends: .build-package
  script:
    - python setup.py sdist bdist_wheel
  only:
    - tags


build-dev:
  extends: .build-package
  script:
    - VERSION_POSTFIX=".dev$(date +%Y%m%d%H%M%S)"
    - echo "$(cat version)${VERSION_POSTFIX}" > version
    - python setup.py sdist bdist_wheel
  except:
    - master
    - tags


sonarcloud-check:
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  tags:
    - rnd-dev
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner


publish:
  stage: publish
  extends: .rnd-dev-runner
  script:
    - twine upload
      --repository-url ${PYPI_URL}
      -u ${PYPI_USER} -p ${PYPI_PASSWORD}
      dist/*
  only:
    - tags
    - develop


.build-package:
  extends: .rnd-dev-runner
  stage: build
  dependencies:
    - install-deps
  artifacts:
    paths:
      - ./dist/
    untracked: true
    expire_in: 1 day

.rnd-dev-runner:
  tags:
    - rnd-dev
